#для доступа к K8s API
apiVersion: v1
kind: ServiceAccount
metadata:
  name: task-manager-sa
  namespace: pet-project
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: task-manager-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: task-manager-binding
subjects:
- kind: ServiceAccount
  name: task-manager-sa
  namespace: pet-project
roleRef:
  kind: ClusterRole
  name: task-manager-role
  apiGroup: rbac.authorization.k8s.io