apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pet-project
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://192.168.0.200:8929/root/python_in_kubernetes.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: pet-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/template/spec/containers/0/image
    - /spec/template/spec/imagePullSecrets
